#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $OpenBSD: Makefile,v 1.5 2014/11/07 22:17:49 schwarze Exp $

PROG=	morse
MAN=	morse.6
COPTS+= -Wno-incompatible-pointer-types-discards-qualifiers

.include <bsd.prog.mk>
